services:

  api:
    build:
      context: .
      dockerfile: OrderTrackingApp.Api/dev.Dockerfile
    command: ["dotnet", "watch", "run"]
    volumes:
      - .:/app
    working_dir: /app/OrderTrackingApp.Api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:8080"

  consumer:
    build:
      context: .
      dockerfile: OrderTrackingApp.Consumer/dev.Dockerfile
    command: ["dotnet", "watch", "run"]
    volumes:
      - .:/app
    working_dir: /app/OrderTrackingApp.Consumer
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
